In [21]:
#!pip install pandas numpy matplotlib scikit-learn statsmodels

In [2]:
import sys
import os
from pathlib import Path
import pandas as pd

# # Add the parent directory to the path to allow imports
sys.path.append(str(Path.cwd()))
# os.chdir(r'C:\Users\hibaa\Documents\GitHub\alert-fatigue')

# from Nirs computer
os.chdir(r'/Users/eveadam/Dropbox/PHD/alert-fatigue/model_pipeline')

from model_pipeline.config import get_config
from model_pipeline.pipeline import run_full_training, run_preprocessing_only
from model_pipeline.models.statsmodels_logit import StatsmodelsLogitModel
from model_pipeline.reporting.coefficients import (
    coefficients_to_or, create_coefficient_summary, filter_significant_coefficients,
    sort_coefficients_by_importance
)

from model_pipeline.evaluation.plots import (
    plot_or_forest, plot_pr_curve, plot_roc_curve, plot_threshold_metrics
)

In [3]:
#!pip install scikit-learn
os.getcwd()
#sys.path.append(str(Path.cwd()))

'/Users/eveadam/Dropbox/PHD/alert-fatigue/model_pipeline'

In [8]:
# Get centralized configuration
config = get_config()
#config["input_csv_path"] = r'C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_10pct.csv'
config["input_csv_path"] = r'C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_100pct.csv'
    
# Display configuration
print(f"Input CSV: {config['input_csv_path']}")
print(f"Date Column: {config['date_column']}")
print(f"Target Column: {config['target_column']}")
print(f"Features: {config['feature_columns']}")
print(f"output dir: {config['output_dir']}")

✓ Configuration validated successfully!
  - Input: ../alert_analysis/data/main_data_2022/df_main_active_adult_renamed_clean_sample_10pct.csv
  - Features: 25 columns
  - Data split: 70% train, 15% eval, 15% test
  - Output: model_pipeline/outputs
Input CSV: C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_100pct.csv
Date Column: time_prescribing_order
Target Column: alert_status_binary
Features: ['age', 'gender', 'hospital_days', 'charlson_score', 'shift_type', 'unit_category_ud', 'hospital_category', 'chronic_med_ud', 'atc_group_ud', 'prescription_day', 'kidney_disease', 'hepatic_disease', 'diabetes_disease', 'ischemic_heart_disease', 'copd_disease', 'cerebrovascular_disease', 'peptic_ulcer_disease', 'dementia_disease', 'oncological_disease', 'hemato_oncological_disease', 'hypertension_disease', 'atrial_fibrillation_disease', 'hyperlipidemia_disease', 'congestive_heart_failure_disease', 'obesity_disease']
output dir: model_pipeline/outputs

In [5]:
# get file path
file_path = config['input_csv_path']
file_path

date_column = config['date_column']
print(date_column)

time_prescribing_order

## Prepare dataset for modeling

In [9]:
df = pd.read_csv(config["input_csv_path"])
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hibaa\\Documents\\GitHub\\alert-fatigue\\alert_analysis\\data\\main_data_2022\\df_main_active_adult_renamed_clean_sample_100pct.csv'

In [7]:
#df.columns.to_list()

In [27]:
# Create new columns 

df['unit_category_ud'] = df['unit_category'].apply(lambda x: 'new_internal' if x in ['Internal', 'Internal-Covid19'] else x)

# df['unit_category_ud'] = df['unit_category_ud'].apply(lambda x: 'new_internal' if x in ['Internal', 'Internal-Covid19'] else x)

In [28]:
df['unit_category_ud'].value_counts()

cross_table = pd.crosstab(df['unit_category_ud'], df['alert_status_binary'], normalize='index')
cross_table

alert_status_binary         0         1
unit_category_ud
Cardiology           0.966815  0.033185
Emergency            0.922262  0.077738
Geriatric            0.968643  0.031357
Gynecology           0.964240  0.035760
Hematology           0.965415  0.034585
Nephrology           0.912633  0.087367
Oncology             0.943860  0.056140
Surgery              0.958090  0.041910
new_internal         0.959653  0.040347

In [29]:
# save new file_ud because  new columns with new unit and alert status binary

df.to_csv( r"C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_100pct_ud.csv", index=False)

## Part 2: run pre-processing

- Split data
- prepere data
- run profiling

In [6]:
config['input_csv_path'] = r"C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_100pct_ud.csv"

In [7]:
# Run preprocessing only:
config['input_csv_path']
# train_df, eval_df, test_df, artifacts = run_preprocessing_only(config)

'C:\\Users\\hibaa\\Documents\\GitHub\\alert-fatigue\\alert_analysis\\data\\main_data_2022\\df_main_active_adult_renamed_clean_sample_100pct_ud.csv'

In [32]:
# Get trainset

train_df.head()

,age,gender,hospital_days,charlson_score,shift_type,unit_category_ud,hospital_category,chronic_med_ud,atc_group_ud,prescription_day,...,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,alert_status_binary
0,78.0,FEMALE,1,0,night,new_internal,Large hospital,0,OTHER,WEEKEND,...,0,0,0,0,0,0,0,0,0,0
1,71.0,FEMALE,1,0,night,Gynecology,Large hospital,0,ANTIBACTERIALS FOR SYSTEMIC USE,WEEKEND,...,0,0,0,0,0,0,0,0,0,0
2,25.0,MALE,1,0,night,Surgery,Large hospital,0,ANALGESICS,WEEKEND,...,0,0,0,0,0,0,0,0,0,0
3,25.0,MALE,1,0,night,Surgery,Large hospital,0,ANALGESICS,WEEKEND,...,0,0,0,0,0,0,0,0,0,0
4,78.0,MALE,1,3,night,new_internal,Large hospital,>=5,OTHER,WEEKEND,...,0,0,0,0,1,0,0,0,0,0

In [33]:
# Get evaluation set

eval_df.head()

,age,gender,hospital_days,charlson_score,shift_type,unit_category_ud,hospital_category,chronic_med_ud,atc_group_ud,prescription_day,...,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,alert_status_binary
1754612,58.0,MALE,1,0,afternoon,Surgery,Small hospital,>=5,OTHER,WEEKDAY,...,0,0,0,0,0,0,0,0,0,0
1754613,58.0,MALE,1,0,afternoon,Surgery,Small hospital,>=5,ANTITHROMBOTIC AGENTS,WEEKDAY,...,0,0,0,0,0,0,0,0,0,0
1754614,58.0,MALE,1,0,afternoon,Surgery,Small hospital,>=5,OTHER,WEEKDAY,...,0,0,0,0,0,0,0,0,0,0
1754615,58.0,MALE,1,0,afternoon,Surgery,Small hospital,>=5,ANTITHROMBOTIC AGENTS,WEEKDAY,...,0,0,0,0,0,0,0,0,0,0
1754616,58.0,MALE,1,0,afternoon,Surgery,Small hospital,>=5,ANTITHROMBOTIC AGENTS,WEEKDAY,...,0,0,0,0,0,0,0,0,0,0

In [34]:
# get artifacts
profile_path = artifacts['profile_path']
run_directory = artifacts['run_directory']
print(profile_path)
print(run_directory)

model_pipeline\outputs\20251013_172721\train_profile_report.html
model_pipeline\outputs\20251013_172721

## Run model training

In [35]:
# Train model
print("Training logistic regression model...")
model = StatsmodelsLogitModel(use_glm=config['use_glm'])
    
train_features = train_df[config['feature_columns']]
train_target = train_df[config['target_column']]
    
model.fit(train_features, train_target)
    
    # Get model summary
model_summary = model.get_model_summary()
aic_bic = model.get_aic_bic()

Training logistic regression model...

C:\Users\hibaa\Documents\GitHub\alert-fatigue\hiba_env\Lib\site-packages\statsmodels\genmod\generalized_linear_model.py:1923: FutureWarning: The bic value is computed using the deviance formula. After 0.13 this will change to the log-likelihood based formula. This change has no impact on the relative rank of models compared using BIC. You can directly access the log-likelihood version using the `bic_llf` attribute. You can suppress this message by calling statsmodels.genmod.generalized_linear_model.SET_USE_BIC_LLF with True to get the LLF-based version now or False to retainthe deviance version.
  warnings.warn(

In [36]:
print(model_summary)

Cleaned Generalized Linear Model Regression Results
===============================================================================
term                                          coef    std err  z         P>|z|  [0.025  0.975]
                                   Intercept -3.4865 0.0195   -179.2050 0.0000 -3.5246 -3.4484
                               gender_FEMALE  0.1121 0.0078     14.3690 0.0000  0.0968  0.1274
                                gender_Other  0.0000 0.0000     52.1272 0.0000  0.0000  0.0000
                        shift_type_afternoon  0.0276 0.0084      3.2843 0.0010  0.0111  0.0441
                            shift_type_night  0.0213 0.0105      2.0180 0.0436  0.0006  0.0419
                            shift_type_Other  0.0000 0.0000     39.5300 0.0000  0.0000  0.0000
                    unit_category_ud_Surgery -0.0140 0.0089     -1.5683 0.1168 -0.0315  0.0035
                 unit_category_ud_Cardiology -0.1676 0.0211     -7.9364 0.0000 -0.2090 -0.1262
                 unit_category_ud_Gynecology -0.0203 0.0221     -0.9150 0.3602 -0.0636  0.0231
                  unit_category_ud_Emergency  0.1865 0.0256      7.2754 0.0000  0.1363  0.2368
                  unit_category_ud_Geriatric -0.6077 0.0407    -14.9462 0.0000 -0.6874 -0.5280
                      unit_category_ud_Other  0.1679 0.0267      6.2777 0.0000  0.1155  0.2204
            hospital_category_Large hospital  0.1797 0.0087     20.5975 0.0000  0.1626  0.1968
            hospital_category_Small hospital  0.3616 0.0104     34.9373 0.0000  0.3413  0.3819
                     hospital_category_Other -0.0000 0.0000     -6.8597 0.0000 -0.0000 -0.0000
                          chronic_med_ud_>=5 -0.2654 0.0105    -25.1687 0.0000 -0.2860 -0.2447
                           chronic_med_ud_<5 -0.3181 0.0225    -14.1448 0.0000 -0.3622 -0.2740
                        chronic_med_ud_Other  0.0000 0.0000      0.4275 0.6690 -0.0000  0.0000
                     atc_group_ud_ANALGESICS  0.2408 0.0105     22.8786 0.0000  0.2201  0.2614
          atc_group_ud_ANTITHROMBOTIC AGENTS  0.0894 0.0144      6.1943 0.0000  0.0611  0.1177
atc_group_ud_ANTIBACTERIALS FOR SYSTEMIC USE  0.6330 0.0127     49.9898 0.0000  0.6082  0.6578
         atc_group_ud_DRUGS USED IN DIABETES  0.2892 0.0152     19.0122 0.0000  0.2594  0.3190
                  atc_group_ud_PSYCHOLEPTICS  0.0667 0.0195      3.4235 0.0006  0.0285  0.1048
                          atc_group_ud_Other -0.0000 0.0000     -4.9802 0.0000 -0.0000 -0.0000
                    prescription_day_WEEKEND  0.0182 0.0089      2.0355 0.0418  0.0007  0.0357
                      prescription_day_Other  0.0000 0.0000      4.2423 0.0000  0.0000  0.0000
                                         age  0.0011 0.0002      4.3768 0.0000  0.0006  0.0015
                               hospital_days  0.0049 0.0003     14.5382 0.0000  0.0042  0.0056
                              charlson_score  0.0293 0.0065      4.4725 0.0000  0.0164  0.0421
                              kidney_disease  0.2384 0.0182     13.1206 0.0000  0.2028  0.2740
                             hepatic_disease  0.0701 0.0268      2.6136 0.0090  0.0175  0.1226
                            diabetes_disease -0.0612 0.0171     -3.5835 0.0003 -0.0947 -0.0277
                      ischemic_heart_disease -0.0310 0.0125     -2.4699 0.0135 -0.0556 -0.0064
                                copd_disease  0.0193 0.0193      1.0002 0.3172 -0.0185  0.0571
                     cerebrovascular_disease -0.0726 0.0143     -5.0770 0.0000 -0.1006 -0.0446
                        peptic_ulcer_disease  0.1516 0.0425      3.5717 0.0004  0.0684  0.2348
                            dementia_disease  0.0293 0.0246      1.1881 0.2348 -0.0190  0.0775
                         oncological_disease -0.0504 0.0205     -2.4630 0.0138 -0.0906 -0.0103
                  hemato_oncological_disease -0.0104 0.0305     -0.3400 0.7338 -0.0702  0.0495
                        hypertension_disease  0.0347 0.0130      2.6656 0.0077  0.0092  0.0602
                 atrial_fibrillation_disease  0.0019 0.0136      0.1429 0.8863 -0.0248  0.0286
                      hyperlipidemia_disease -0.0231 0.0102     -2.2576 0.0240 -0.0431 -0.0030
            congestive_heart_failure_disease -0.0700 0.0179     -3.9108 0.0001 -0.1050 -0.0349
                             obesity_disease -0.1183 0.0142     -8.3611 0.0000 -0.1461 -0.0906

In [37]:
 # Get coefficients and convert to odds ratios
print("Analyzing coefficients...")
coef_df = model.get_coefficients()
or_df = coefficients_to_or(coef_df)
    
# Sort coefficients by importance
or_df_sorted = sort_coefficients_by_importance(or_df, method='odds_ratio')
    
# Filter significant coefficients
significant_coef = filter_significant_coefficients(or_df)
    
# Create coefficient summary
coef_summary = create_coefficient_summary(or_df)

Analyzing coefficients...

In [38]:
coef_summary

{'total_features': 44,
 'significant_features': np.int64(37),
 'non_significant_features': np.int64(7),
 'significance_breakdown': {'***': 29, 'ns': 7, '*': 5, '**': 3},
 'odds_ratio_stats': {'min': 0.5446119827490056,
  'max': 1.8832542237973804,
  'mean': 1.0445855679553926,
  'median': 1.0019492107480157},
 'factor_types': {'protective_factors': 15, 'risk_factors': 25},
 'p_value_stats': {'min': 0.0,
  'max': 0.8863313534619345,
  'mean': 0.0789535925144743,
  'median': 4.182684108095249e-06}}

Create Odds ratio forest plot

In [39]:
forest_plot_path = os.path.join(run_directory, "coefficients_forest_test.png")

plot_or_forest(or_df_sorted, forest_plot_path, 
                   title="Forest Plot of Odds Ratios - Alert Fatigue Model")

'model_pipeline\\outputs\\20251013_172721\\coefficients_forest_test.png'

In [40]:
or_df_sorted

,feature,odds_ratio,odds_ratio_formatted,ci_formatted,odds_ratio_ci_lower,odds_ratio_ci_upper,coefficient,std_error,p_value,p_value_formatted,significant,significance_level,interpretation,distance_from_null
0,Intercept,0.030607,0.031,"(0.029, 0.032)",0.029462,0.031797,-3.486511e+00,1.945543e-02,0.000000e+00,< 0.001,True,***,strongly decreases odds,9.693925e-01
20,atc_group_ud_ANTIBACTERIALS FOR SYSTEMIC USE,1.883254,1.883,"(1.837, 1.931)",1.837090,1.930578,6.330013e-01,1.266261e-02,0.000000e+00,< 0.001,True,***,moderately increases odds,8.832542e-01
10,unit_category_ud_Geriatric,0.544612,0.545,"(0.503, 0.590)",0.502897,0.589787,-6.076817e-01,4.065796e-02,1.649111e-50,< 0.001,True,***,moderately decreases odds,4.553880e-01
13,hospital_category_Small hospital,1.435642,1.436,"(1.407, 1.465)",1.406812,1.465063,3.616121e-01,1.035032e-02,2.019189e-267,< 0.001,True,***,slightly increases odds,4.356420e-01
21,atc_group_ud_DRUGS USED IN DIABETES,1.335311,1.335,"(1.296, 1.376)",1.296093,1.375716,2.891644e-01,1.520941e-02,1.351395e-80,< 0.001,True,***,slightly increases odds,3.353113e-01
16,chronic_med_ud_<5,0.727516,0.728,"(0.696, 0.760)",0.696144,0.760302,-3.181189e-01,2.249013e-02,2.010280e-45,< 0.001,True,***,slightly decreases odds,2.724837e-01
18,atc_group_ud_ANALGESICS,1.272222,1.272,"(1.246, 1.299)",1.246250,1.298735,2.407650e-01,1.052360e-02,7.594561e-116,< 0.001,True,***,slightly increases odds,2.722220e-01
29,kidney_disease,1.269214,1.269,"(1.225, 1.315)",1.224810,1.315228,2.383979e-01,1.816969e-02,2.508122e-39,< 0.001,True,***,slightly increases odds,2.692141e-01
15,chronic_med_ud_>=5,0.766931,0.767,"(0.751, 0.783)",0.751246,0.782944,-2.653579e-01,1.054316e-02,8.813870e-140,< 0.001,True,***,slightly decreases odds,2.330686e-01
9,unit_category_ud_Emergency,1.205081,1.205,"(1.146, 1.267)",1.146016,1.267191,1.865471e-01,2.564098e-02,3.455212e-13,< 0.001,True,***,slightly increases odds,2.050814e-01
12,hospital_category_Large hospital,1.196853,1.197,"(1.177, 1.217)",1.176562,1.217494,1.796957e-01,8.724140e-03,2.888518e-94,< 0.001,True,***,slightly increases odds,1.968531e-01
11,unit_category_ud_Other,1.182848,1.183,"(1.122, 1.247)",1.122431,1.246518,1.679255e-01,2.674966e-02,3.436884e-10,< 0.001,True,***,slightly increases odds,1.828485e-01
35,peptic_ulcer_disease,1.163729,1.164,"(1.071, 1.265)",1.070817,1.264702,1.516294e-01,4.245338e-02,3.547151e-04,< 0.001,True,***,slightly increases odds,1.637288e-01
7,unit_category_ud_Cardiology,0.845687,0.846,"(0.811, 0.881)",0.811397,0.881426,-1.676060e-01,2.111859e-02,2.080992e-15,< 0.001,True,***,slightly decreases odds,1.543130e-01
1,gender_FEMALE,1.118673,1.119,"(1.102, 1.136)",1.101691,1.135916,1.121431e-01,7.804540e-03,8.103844e-47,< 0.001,True,***,slightly increases odds,1.186730e-01
43,obesity_disease,0.888386,0.888,"(0.864, 0.913)",0.864079,0.913377,-1.183490e-01,1.415466e-02,6.211888e-17,< 0.001,True,***,slightly decreases odds,1.116140e-01
19,atc_group_ud_ANTITHROMBOTIC AGENTS,1.093497,1.093,"(1.063, 1.125)",1.063004,1.124864,8.938064e-02,1.442961e-02,5.856292e-10,< 0.001,True,***,slightly increases odds,9.349680e-02
30,hepatic_disease,1.072586,1.073,"(1.018, 1.130)",1.017679,1.130456,7.007250e-02,2.681087e-02,8.959782e-03,0.009,True,**,slightly increases odds,7.258594e-02
34,cerebrovascular_disease,0.930006,0.930,"(0.904, 0.956)",0.904314,0.956427,-7.256475e-02,1.429296e-02,3.835304e-07,< 0.001,True,***,slightly decreases odds,6.999447e-02
22,atc_group_ud_PSYCHOLEPTICS,1.068931,1.069,"(1.029, 1.111)",1.028906,1.110512,6.665887e-02,1.947111e-02,6.182597e-04,< 0.001,True,***,slightly increases odds,6.893077e-02
42,congestive_heart_failure_disease,0.932425,0.932,"(0.900, 0.966)",0.900297,0.965700,-6.996655e-02,1.789038e-02,9.197265e-05,< 0.001,True,***,slightly decreases odds,6.757499e-02
31,diabetes_disease,0.940647,0.941,"(0.910, 0.973)",0.909688,0.972660,-6.118712e-02,1.707484e-02,3.390642e-04,< 0.001,True,***,slightly decreases odds,5.935279e-02
37,oncological_disease,0.950817,0.951,"(0.913, 0.990)",0.913414,0.989752,-5.043356e-02,2.047626e-02,1.377699e-02,0.014,True,*,slightly decreases odds,4.918290e-02
39,hypertension_disease,1.035291,1.035,"(1.009, 1.062)",1.009224,1.062032,3.468268e-02,1.301108e-02,7.684493e-03,0.008,True,**,slightly increases odds,3.529113e-02
32,ischemic_heart_disease,0.969480,0.969,"(0.946, 0.994)",0.945925,0.993621,-3.099561e-02,1.254931e-02,1.351485e-02,0.014,True,*,slightly decreases odds,3.052017e-02
28,charlson_score,1.029692,1.030,"(1.017, 1.043)",1.016573,1.042981,2.926005e-02,6.542187e-03,7.730346e-06,< 0.001,True,***,slightly increases odds,2.969234e-02
36,dementia_disease,1.029691,1.030,"(0.981, 1.081)",0.981171,1.080610,2.925862e-02,2.462641e-02,2.347942e-01,0.235,False,ns,Not significant,2.969086e-02
3,shift_type_afternoon,1.027983,1.028,"(1.011, 1.045)",1.011190,1.045054,2.759835e-02,8.403233e-03,1.022525e-03,0.001,True,**,slightly increases odds,2.798272e-02
41,hyperlipidemia_disease,0.977199,0.977,"(0.958, 0.997)",0.957827,0.996964,-2.306460e-02,1.021651e-02,2.397179e-02,0.024,True,*,slightly decreases odds,2.280064e-02
4,shift_type_night,1.021498,1.021,"(1.001, 1.043)",1.000612,1.042820,2.127027e-02,1.054002e-02,4.358636e-02,0.044,True,*,slightly increases odds,2.149809e-02
8,unit_category_ud_Gynecology,0.979952,0.980,"(0.938, 1.023)",0.938350,1.023399,-2.025161e-02,2.213347e-02,3.602039e-01,0.360,False,ns,Not significant,2.004792e-02
33,copd_disease,1.019493,1.019,"(0.982, 1.059)",0.981644,1.058801,1.930526e-02,1.930212e-02,3.172318e-01,0.317,False,ns,Not significant,1.949281e-02
24,prescription_day_WEEKEND,1.018331,1.018,"(1.001, 1.036)",1.000674,1.036301,1.816550e-02,8.924539e-03,4.180513e-02,0.042,True,*,slightly increases odds,1.833149e-02
6,unit_category_ud_Surgery,0.986098,0.986,"(0.969, 1.004)",0.968996,1.003502,-1.399931e-02,8.926361e-03,1.168085e-01,0.117,False,ns,Not significant,1.390178e-02
38,hemato_oncological_disease,0.989672,0.990,"(0.932, 1.051)",0.932188,1.050701,-1.038126e-02,3.053071e-02,7.338364e-01,0.734,False,ns,Not significant,1.032756e-02
27,hospital_days,1.004923,1.005,"(1.004, 1.006)",1.004258,1.005588,4.910649e-03,3.377767e-04,6.944163e-48,< 0.001,True,***,slightly increases odds,4.922726e-03
40,atrial_fibrillation_disease,1.001949,1.002,"(0.976, 1.029)",0.975551,1.029061,1.947314e-03,1.362254e-02,8.863314e-01,0.886,False,ns,Not significant,1.949211e-03
26,age,1.001057,1.001,"(1.001, 1.002)",1.000583,1.001530,1.056245e-03,2.413304e-04,1.204583e-05,< 0.001,True,***,slightly increases odds,1.056803e-03
2,gender_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,6.536399e-15,1.253931e-16,0.000000e+00,< 0.001,True,***,slightly increases odds,6.439294e-15
5,shift_type_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,8.446419e-16,2.136710e-17,0.000000e+00,< 0.001,True,***,slightly increases odds,8.881784e-16
14,hospital_category_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,-8.739850e-17,1.274077e-17,6.898190e-12,< 0.001,True,***,slightly decreases odds,1.110223e-16
25,prescription_day_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,6.602707e-17,1.556391e-17,2.212235e-05,< 0.001,True,***,slightly decreases odds,0.000000e+00
17,chronic_med_ud_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,7.064308e-18,1.652299e-17,6.689831e-01,0.669,False,ns,Not significant,0.000000e+00
23,atc_group_ud_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,-5.390461e-17,1.082368e-17,6.350221e-07,< 0.001,True,***,slightly decreases odds,0.000000e+00

In [41]:
train_df[config['feature_columns']].value_counts()

age    gender  hospital_days  charlson_score  shift_type  unit_category_ud  hospital_category  chronic_med_ud  atc_group_ud                     prescription_day  kidney_disease  hepatic_disease  diabetes_disease  ischemic_heart_disease  copd_disease  cerebrovascular_disease  peptic_ulcer_disease  dementia_disease  oncological_disease  hemato_oncological_disease  hypertension_disease  atrial_fibrillation_disease  hyperlipidemia_disease  congestive_heart_failure_disease  obesity_disease
30.0   FEMALE  1              0               morning     Gynecology        Large hospital     0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  166
28.0   FEMALE  1              0               morning     Gynecology        Large hospital     0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  157
26.0   FEMALE  1              0               morning     Gynecology        Large hospital     0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  156
32.0   FEMALE  1              0               morning     Gynecology        Large hospital     0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  153
47.0   MALE    148            0               morning     Surgery           Large hospital     0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  149
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
117.0  FEMALE  1              1               afternoon   new_internal      Small hospital     <5              ANTITHROMBOTIC AGENTS            WEEKDAY           0               0                0                 0                       0             1                        0                     0                 0                    0                           1                     0                            0                       0                                 0                    1
               5              1               morning     new_internal      Medium hospital    0               ANALGESICS                       WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           1                     0                            1                       0                                 0                    1
                                                                                                                                                WEEKEND           0               0                0                 0                       0             0                        0                     0                 0                    0                           1                     0                            1                       0                                 0                    1
19.0   MALE    1              0               morning     new_internal      Medium hospital    0               PSYCHOLEPTICS                    WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                    1
                                                                                                               ANTIBACTERIALS FOR SYSTEMIC USE  WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                    1
Name: count, Length: 585550, dtype: int64

In [21]:
# test_code