In [1]:
#!pip install pandas numpy matplotlib scikit-learn statsmodels

In [2]:
import sys
import os
from pathlib import Path
import pandas as pd

# # Add the parent directory to the path to allow imports
sys.path.append(str(Path.cwd()))
os.chdir(r'C:\Users\hibaa\Documents\GitHub\alert-fatigue')

# from Nirs computer
#os.chdir(r'/Users/eveadam/Dropbox/PHD/alert-fatigue/model_pipeline')

from model_pipeline.config import get_config
from model_pipeline.pipeline import run_full_training, run_preprocessing_only
from model_pipeline.models.statsmodels_logit import StatsmodelsLogitModel
from model_pipeline.reporting.coefficients import (
    coefficients_to_or, create_coefficient_summary, filter_significant_coefficients,
    sort_coefficients_by_importance
)

from model_pipeline.evaluation.plots import (
    plot_or_forest, plot_pr_curve, plot_roc_curve, plot_threshold_metrics
)

In [3]:
#!pip install scikit-learn
os.getcwd()
#sys.path.append(str(Path.cwd()))

'C:\\Users\\hibaa\\Documents\\GitHub\\alert-fatigue'

In [4]:
# Get centralized configuration
config = get_config()
config["input_csv_path"] = r'C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_10pct.csv'
    
# Display configuration
print(f"Input CSV: {config['input_csv_path']}")
print(f"Date Column: {config['date_column']}")
print(f"Target Column: {config['target_column']}")
print(f"Features: {config['feature_columns']}")
print(f"output dir: {config['output_dir']}")

⚠️  WARNING: Input file not found: ../alert_analysis/data/main_data_2022/df_main_active_adult_renamed_clean_sample_10pct.csv
   This will cause an error when running the pipeline.
✓ Configuration validated successfully!
  - Input: ../alert_analysis/data/main_data_2022/df_main_active_adult_renamed_clean_sample_10pct.csv
  - Features: 25 columns
  - Data split: 70% train, 15% eval, 15% test
  - Output: model_pipeline\outputs
Input CSV: C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_10pct.csv
Date Column: time_prescribing_order
Target Column: alert_status_binary
Features: ['age', 'gender', 'hospital_days', 'charlson_score', 'shift_type', 'unit_category_ud', 'hospital_category', 'chronic_med_ud', 'atc_group_ud', 'prescription_day', 'kidney_disease', 'hepatic_disease', 'diabetes_disease', 'ischemic_heart_disease', 'copd_disease', 'cerebrovascular_disease', 'peptic_ulcer_disease', 'dementia_disease', 'oncological_disease', 'hemato_oncological_disease', 'hypertension_disease', 'atrial_fibrillation_disease', 'hyperlipidemia_disease', 'congestive_heart_failure_disease', 'obesity_disease']
output dir: model_pipeline\outputs

In [5]:
# get file path
file_path = config['input_csv_path']
file_path

date_column = config['date_column']
print(date_column)

time_prescribing_order

## Prepare dataset for modeling

In [6]:
df = pd.read_csv(config["input_csv_path"])
df.head()

C:\Users\hibaa\AppData\Local\Temp\ipykernel_4120\3119677392.py:1: DtypeWarning: Columns (35,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(config["input_csv_path"])

,hospital_code,hospital_name,unit_category,severity_level_to_stop_order,medical_record,admission_num,age,gender,sector,time_prescribing_order,...,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,alert_status_binary
0,237,CARMEL,Internal,Active Mode,1993912,2.022021e+09,65.0,MALE,DOCTOR,2022-07-19T11:36:06Z,...,0,0,1,0,0,0,0,0,0,0
1,24,SOROKA,Internal,Active Mode,8530932,2.022000e+09,84.0,FEMALE,NURSE,2022-01-03T23:43:44Z,...,0,0,0,0,1,0,0,0,1,0
2,23,KAPLAN,Surgery,Active Mode,4089337,2.022006e+09,83.0,MALE,DOCTOR,2022-02-14T12:35:37Z,...,0,0,0,0,0,0,0,0,0,0
3,23,KAPLAN,Internal,Active Mode,4453476,2.022036e+09,76.0,MALE,DOCTOR,2022-09-16T10:34:13Z,...,0,0,1,0,1,0,0,0,0,0
4,26,EMEK,Surgery,Active Mode,3527173,2.022107e+09,65.0,FEMALE,DOCTOR,2022-10-01T20:00:56Z,...,0,0,1,0,1,1,0,0,0,0

In [7]:
#df.columns.to_list()

In [8]:
## Create new columns

df['unit_category_ud'] = df['unit_category'].apply(lambda x: 'new_internal' if x in ['Internal', 'Internal-Covid19'] else x)

# df['unit_category_ud'] = df['unit_category_ud'].apply(lambda x: 'new_internal' if x in ['Internal', 'Internal-Covid19'] else x)

In [18]:
df['unit_category_ud'].value_counts()

cross_table = pd.crosstab(df['unit_category_ud'], df['alert_status_binary'], normalize='index')
cross_table

alert_status_binary         0         1
unit_category_ud
Cardiology           0.968587  0.031413
Emergency            0.922403  0.077597
Geriatric            0.969405  0.030595
Gynecology           0.964608  0.035392
Hematology           0.963170  0.036830
Nephrology           0.911890  0.088110
Oncology             0.960938  0.039062
Surgery              0.957135  0.042865
new_internal         0.960271  0.039729

In [9]:
df.to_csv( r"C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_10pct_ud.csv", index=False)

## Part 2: run pre-processing

- Split data
- prepere data
- run profiling

In [10]:
config['input_csv_path'] = r"C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_clean_sample_10pct_ud.csv"

In [11]:
# Run preprocessing only:

train_df, eval_df, test_df, artifacts = run_preprocessing_only(config)

Running preprocessing pipeline...
Loading data...
✓ Data loaded: 250,658 rows, 27 columns

Splitting data...
✓ Data split: Train=175,460, Eval=37,598, Test=37,600

Preprocessing data...
  Preprocessing configuration:
    - Impute numeric: True
    - Scale numeric: False
    - Rare category threshold: 0.01
  Fitting preprocessor on training data...
  Preprocessing details:
    - Numeric columns: 18
    - Categorical columns: 7
    - Numeric imputation applied to: age, hospital_days, charlson_score, kidney_disease, hepatic_disease, diabetes_disease, ischemic_heart_disease, copd_disease, cerebrovascular_disease, peptic_ulcer_disease, dementia_disease, oncological_disease, hemato_oncological_disease, hypertension_disease, atrial_fibrillation_disease, hyperlipidemia_disease, congestive_heart_failure_disease, obesity_disease
    - No missing values found in numeric columns
    - Categorical processing applied to: gender, shift_type, unit_category_ud, hospital_category, chronic_med_ud, atc_group_ud, prescription_day
      - gender: 2 levels preserved
      - shift_type: 3 levels preserved
      - unit_category_ud: 6 levels preserved
      - hospital_category: 3 levels preserved
      - chronic_med_ud: 3 levels preserved
      - atc_group_ud: 6 levels preserved
      - prescription_day: 2 levels preserved
  Transforming data...
  Final processed shapes:
    - Train: (175460, 26)
    - Eval: (37598, 26)
    - Test: (37600, 26)

Generating profile report...

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                  | 0/26 [00:00<?, ?it/s]
 19%|██████████████▏                                                           | 5/26 [00:02<00:11,  1.86it/s]
 23%|█████████████████                                                         | 6/26 [00:03<00:10,  1.93it/s]
100%|█████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.88it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

✓ Profile report saved to: model_pipeline\outputs\20251013_110426\train_profile_report.html

✓ Preprocessing completed successfully!

In [12]:
# Get trainset

train_df.head()

,age,gender,hospital_days,charlson_score,shift_type,unit_category_ud,hospital_category,chronic_med_ud,atc_group_ud,prescription_day,...,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,alert_status_binary
0,71.0,FEMALE,1,0,night,Gynecology,Large hospitals,0,ANTIBACTERIALS FOR SYSTEMIC USE,WEEKEND,...,0,0,0,0,0,0,0,0,0,0
1,74.0,FEMALE,2,2,night,new_internal,Medium hospitals,<5,OTHER,WEEKEND,...,0,0,1,0,0,0,0,0,0,0
2,74.0,FEMALE,2,2,night,new_internal,Medium hospitals,0,ANALGESICS,WEEKEND,...,0,0,1,0,0,0,0,0,0,0
3,90.0,MALE,1,5,night,new_internal,Large hospitals,>=5,OTHER,WEEKEND,...,0,0,0,0,1,0,0,0,0,0
4,69.0,MALE,16,6,night,Surgery,Large hospitals,0,ANALGESICS,WEEKEND,...,0,0,0,0,1,0,0,0,0,0

In [13]:
# Get evaluation set

eval_df.head()

,age,gender,hospital_days,charlson_score,shift_type,unit_category_ud,hospital_category,chronic_med_ud,atc_group_ud,prescription_day,...,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,alert_status_binary
175460,88.0,FEMALE,1,5,afternoon,new_internal,Large hospitals,<5,OTHER,WEEKDAY,...,0,0,0,0,1,0,0,0,0,0
175461,40.0,MALE,1,0,afternoon,Emergency,Small hospitals,0,OTHER,WEEKDAY,...,0,0,0,0,0,0,0,0,0,0
175462,85.0,FEMALE,1,6,afternoon,new_internal,Large hospitals,>=5,DRUGS USED IN DIABETES,WEEKDAY,...,0,0,0,0,1,0,1,1,0,0
175463,85.0,FEMALE,1,6,afternoon,new_internal,Large hospitals,>=5,OTHER,WEEKDAY,...,0,0,0,0,1,0,1,1,0,0
175464,85.0,FEMALE,1,6,afternoon,new_internal,Large hospitals,>=5,OTHER,WEEKDAY,...,0,0,0,0,1,0,1,1,0,0

In [14]:
# get artifacts
profile_path = artifacts['profile_path']
run_directory = artifacts['run_directory']
print(profile_path)
print(run_directory)

model_pipeline\outputs\20251013_110426\train_profile_report.html
model_pipeline\outputs\20251013_110426

## Run model training

In [15]:
# Train model
print("Training logistic regression model...")
model = StatsmodelsLogitModel(use_glm=config['use_glm'])
    
train_features = train_df[config['feature_columns']]
train_target = train_df[config['target_column']]
    
model.fit(train_features, train_target)
    
    # Get model summary
model_summary = model.get_model_summary()
aic_bic = model.get_aic_bic()

Training logistic regression model...

C:\Users\hibaa\Documents\GitHub\alert-fatigue\hiba_env\Lib\site-packages\statsmodels\genmod\generalized_linear_model.py:1923: FutureWarning: The bic value is computed using the deviance formula. After 0.13 this will change to the log-likelihood based formula. This change has no impact on the relative rank of models compared using BIC. You can directly access the log-likelihood version using the `bic_llf` attribute. You can suppress this message by calling statsmodels.genmod.generalized_linear_model.SET_USE_BIC_LLF with True to get the LLF-based version now or False to retainthe deviance version.
  warnings.warn(

In [16]:
print(model_summary)

Cleaned Generalized Linear Model Regression Results
===============================================================================
term                                          coef    std err  z        P>|z|  [0.025  0.975]
                                   Intercept -3.4765 0.0614   -56.6635 0.0000 -3.5968 -3.3563
                               gender_FEMALE  0.1276 0.0247     5.1607 0.0000  0.0791  0.1761
                                gender_Other -0.0000 0.0000    -0.6082 0.5431 -0.0000  0.0000
                        shift_type_afternoon  0.0138 0.0266     0.5188 0.6039 -0.0383  0.0659
                            shift_type_night  0.0148 0.0334     0.4449 0.6564 -0.0506  0.0803
                            shift_type_Other  0.0000 0.0000     0.9703 0.3319 -0.0000  0.0000
                    unit_category_ud_Surgery  0.0190 0.0282     0.6739 0.5004 -0.0362  0.0742
                 unit_category_ud_Cardiology -0.1957 0.0688    -2.8462 0.0044 -0.3305 -0.0609
                 unit_category_ud_Gynecology -0.0282 0.0690    -0.4089 0.6826 -0.1635  0.1071
                  unit_category_ud_Emergency  0.1391 0.0825     1.6859 0.0918 -0.0226  0.3007
                  unit_category_ud_Geriatric -0.6793 0.1334    -5.0925 0.0000 -0.9407 -0.4178
                      unit_category_ud_Other  0.1479 0.0850     1.7399 0.0819 -0.0187  0.3145
           hospital_category_Large hospitals  0.2093 0.0276     7.5830 0.0000  0.1552  0.2633
           hospital_category_Small hospitals  0.3771 0.0328    11.4985 0.0000  0.3128  0.4414
                     hospital_category_Other  0.0000 0.0000     3.1096 0.0019  0.0000  0.0000
                          chronic_med_ud_>=5 -0.2511 0.0336    -7.4753 0.0000 -0.3169 -0.1852
                           chronic_med_ud_<5 -0.2828 0.0712    -3.9744 0.0001 -0.4222 -0.1433
                        chronic_med_ud_Other -0.0000 0.0000    -1.4700 0.1416 -0.0000  0.0000
                     atc_group_ud_ANALGESICS  0.2752 0.0331     8.3252 0.0000  0.2104  0.3399
          atc_group_ud_ANTITHROMBOTIC AGENTS  0.0643 0.0464     1.3865 0.1656 -0.0266  0.1552
atc_group_ud_ANTIBACTERIALS FOR SYSTEMIC USE  0.6631 0.0398    16.6561 0.0000  0.5850  0.7411
         atc_group_ud_DRUGS USED IN DIABETES  0.2687 0.0491     5.4711 0.0000  0.1724  0.3649
                  atc_group_ud_PSYCHOLEPTICS  0.0788 0.0612     1.2873 0.1980 -0.0412  0.1988
                          atc_group_ud_Other -0.0000 0.0000    -4.8651 0.0000 -0.0000 -0.0000
                    prescription_day_WEEKEND  0.0097 0.0284     0.3397 0.7341 -0.0461  0.0654
                      prescription_day_Other -0.0000 0.0000    -2.2008 0.0278 -0.0000 -0.0000
                                         age  0.0003 0.0008     0.3866 0.6991 -0.0012  0.0018
                               hospital_days  0.0057 0.0010     5.4837 0.0000  0.0036  0.0077
                              charlson_score -0.0007 0.0216    -0.0347 0.9724 -0.0430  0.0415
                              kidney_disease  0.3440 0.0588     5.8465 0.0000  0.2287  0.4593
                             hepatic_disease  0.1475 0.0851     1.7327 0.0832 -0.0194  0.3144
                            diabetes_disease -0.0152 0.0555    -0.2734 0.7846 -0.1239  0.0936
                      ischemic_heart_disease -0.0175 0.0399    -0.4398 0.6600 -0.0957  0.0606
                                copd_disease  0.1022 0.0609     1.6783 0.0933 -0.0171  0.2215
                     cerebrovascular_disease -0.0415 0.0461    -0.9006 0.3678 -0.1320  0.0489
                        peptic_ulcer_disease  0.3475 0.1264     2.7483 0.0060  0.0997  0.5953
                            dementia_disease  0.0146 0.0797     0.1837 0.8542 -0.1416  0.1708
                         oncological_disease -0.0539 0.0665    -0.8096 0.4182 -0.1842  0.0765
                  hemato_oncological_disease -0.0125 0.0989    -0.1264 0.8994 -0.2063  0.1813
                        hypertension_disease  0.0436 0.0415     1.0509 0.2933 -0.0377  0.1248
                 atrial_fibrillation_disease  0.0140 0.0432     0.3233 0.7465 -0.0708  0.0987
                      hyperlipidemia_disease -0.0196 0.0327    -0.5986 0.5495 -0.0836  0.0445
            congestive_heart_failure_disease -0.0344 0.0570    -0.6038 0.5460 -0.1463  0.0774
                             obesity_disease -0.1777 0.0458    -3.8819 0.0001 -0.2675 -0.0880

In [17]:
 # Get coefficients and convert to odds ratios
print("Analyzing coefficients...")
coef_df = model.get_coefficients()
or_df = coefficients_to_or(coef_df)
    
# Sort coefficients by importance
or_df_sorted = sort_coefficients_by_importance(or_df, method='odds_ratio')
    
# Filter significant coefficients
significant_coef = filter_significant_coefficients(or_df)
    
# Create coefficient summary
coef_summary = create_coefficient_summary(or_df)

Analyzing coefficients...

In [18]:
coef_summary

{'total_features': 44,
 'significant_features': np.int64(18),
 'non_significant_features': np.int64(26),
 'significance_breakdown': {'ns': 26, '***': 14, '**': 3, '*': 1},
 'odds_ratio_stats': {'min': 0.50698498190283,
  'max': 1.940715815991973,
  'mean': 1.059476704133162,
  'median': 1.0056936261373641},
 'factor_types': {'protective_factors': 18, 'risk_factors': 25},
 'p_value_stats': {'min': 0.0,
  'max': 0.972357168281989,
  'mean': 0.2895157735631246,
  'median': 0.11742535382522222}}

Create Odds ratio forest plot

In [19]:
forest_plot_path = os.path.join(run_directory, "coefficients_forest_test.png")

plot_or_forest(or_df_sorted, forest_plot_path, 
                   title="Forest Plot of Odds Ratios - Alert Fatigue Model")

'model_pipeline\\outputs\\20251013_110426\\coefficients_forest_test.png'

In [20]:
or_df_sorted

,feature,odds_ratio,odds_ratio_formatted,ci_formatted,odds_ratio_ci_lower,odds_ratio_ci_upper,coefficient,std_error,p_value,p_value_formatted,significant,significance_level,interpretation,distance_from_null
0,Intercept,0.030914,0.031,"(0.027, 0.035)",0.027412,0.034865,-3.476533e+00,6.135405e-02,0.000000e+00,< 0.001,True,***,strongly decreases odds,9.690856e-01
20,atc_group_ud_ANTIBACTERIALS FOR SYSTEMIC USE,1.940716,1.941,"(1.795, 2.098)",1.795051,2.098201,6.630569e-01,3.980863e-02,2.732314e-62,< 0.001,True,***,moderately increases odds,9.407158e-01
10,unit_category_ud_Geriatric,0.506985,0.507,"(0.390, 0.658)",0.390352,0.658467,-6.792739e-01,1.333866e-01,3.533368e-07,< 0.001,True,***,moderately decreases odds,4.930150e-01
13,hospital_category_Small hospitals,1.458087,1.458,"(1.367, 1.555)",1.367307,1.554894,3.771250e-01,3.279765e-02,1.341732e-30,< 0.001,True,***,slightly increases odds,4.580865e-01
35,peptic_ulcer_disease,1.415473,1.415,"(1.105, 1.814)",1.104804,1.813503,3.474640e-01,1.264290e-01,5.990627e-03,0.006,True,**,slightly increases odds,4.154733e-01
29,kidney_disease,1.410583,1.411,"(1.257, 1.583)",1.256941,1.583006,3.440033e-01,5.883897e-02,5.019593e-09,< 0.001,True,***,slightly increases odds,4.105833e-01
18,atc_group_ud_ANALGESICS,1.316747,1.317,"(1.234, 1.405)",1.234151,1.404871,2.751646e-01,3.305213e-02,8.420757e-17,< 0.001,True,***,slightly increases odds,3.167474e-01
21,atc_group_ud_DRUGS USED IN DIABETES,1.308221,1.308,"(1.188, 1.440)",1.188178,1.440391,2.686682e-01,4.910640e-02,4.471416e-08,< 0.001,True,***,slightly increases odds,3.082210e-01
16,chronic_med_ud_<5,0.753681,0.754,"(0.656, 0.866)",0.655576,0.866467,-2.827867e-01,7.115187e-02,7.055411e-05,< 0.001,True,***,slightly decreases odds,2.463194e-01
12,hospital_category_Large hospitals,1.232754,1.233,"(1.168, 1.301)",1.167852,1.301263,2.092508e-01,2.759468e-02,3.376213e-14,< 0.001,True,***,slightly increases odds,2.327542e-01
15,chronic_med_ud_>=5,0.777982,0.778,"(0.728, 0.831)",0.728421,0.830914,-2.510522e-01,3.358409e-02,7.701033e-14,< 0.001,True,***,slightly decreases odds,2.220182e-01
7,unit_category_ud_Cardiology,0.822237,0.822,"(0.719, 0.941)",0.718558,0.940875,-1.957270e-01,6.876779e-02,4.424407e-03,0.004,True,**,slightly decreases odds,1.777634e-01
43,obesity_disease,0.837159,0.837,"(0.765, 0.916)",0.765304,0.915761,-1.777409e-01,4.578733e-02,1.036527e-04,< 0.001,True,***,slightly decreases odds,1.628407e-01
11,unit_category_ud_Other,1.159370,1.159,"(0.981, 1.370)",0.981471,1.369513,1.478764e-01,8.499084e-02,8.187477e-02,0.082,False,ns,Not significant,1.593696e-01
30,hepatic_disease,1.158959,1.159,"(0.981, 1.369)",0.980832,1.369434,1.475218e-01,8.514210e-02,8.315719e-02,0.083,False,ns,Not significant,1.589585e-01
9,unit_category_ud_Emergency,1.149200,1.149,"(0.978, 1.351)",0.977648,1.350855,1.390660e-01,8.248698e-02,9.181228e-02,0.092,False,ns,Not significant,1.491999e-01
1,gender_FEMALE,1.136111,1.136,"(1.082, 1.193)",1.082362,1.192529,1.276109e-01,2.472765e-02,2.460856e-07,< 0.001,True,***,slightly increases odds,1.361109e-01
33,copd_disease,1.107553,1.108,"(0.983, 1.248)",0.983001,1.247887,1.021535e-01,6.086755e-02,9.329016e-02,0.093,False,ns,Not significant,1.075535e-01
22,atc_group_ud_PSYCHOLEPTICS,1.081990,1.082,"(0.960, 1.220)",0.959660,1.219915,7.880235e-02,6.121484e-02,1.979870e-01,0.198,False,ns,Not significant,8.199044e-02
19,atc_group_ud_ANTITHROMBOTIC AGENTS,1.066424,1.066,"(0.974, 1.168)",0.973749,1.167919,6.431084e-02,4.638494e-02,1.656067e-01,0.166,False,ns,Not significant,6.642383e-02
37,oncological_disease,0.947573,0.948,"(0.832, 1.080)",0.831751,1.079523,-5.385111e-02,6.651683e-02,4.181780e-01,0.418,False,ns,Not significant,5.242682e-02
39,hypertension_disease,1.044534,1.045,"(0.963, 1.133)",0.963013,1.132956,4.357123e-02,4.145950e-02,2.932886e-01,0.293,False,ns,Not significant,4.453440e-02
34,cerebrovascular_disease,0.959309,0.959,"(0.876, 1.050)",0.876383,1.050081,-4.154228e-02,4.612801e-02,3.678081e-01,0.368,False,ns,Not significant,4.069122e-02
42,congestive_heart_failure_disease,0.966138,0.966,"(0.864, 1.080)",0.863931,1.080438,-3.444810e-02,5.704938e-02,5.459570e-01,0.546,False,ns,Not significant,3.386152e-02
8,unit_category_ud_Gynecology,0.972165,0.972,"(0.849, 1.113)",0.849126,1.113033,-2.822923e-02,6.904103e-02,6.826305e-01,0.683,False,ns,Not significant,2.783451e-02
41,hyperlipidemia_disease,0.980631,0.981,"(0.920, 1.045)",0.919797,1.045489,-1.955892e-02,3.267581e-02,5.494563e-01,0.549,False,ns,Not significant,1.936889e-02
6,unit_category_ud_Surgery,1.019153,1.019,"(0.964, 1.077)",0.964438,1.076972,1.897198e-02,2.815429e-02,5.004018e-01,0.500,False,ns,Not significant,1.915310e-02
32,ischemic_heart_disease,0.982608,0.983,"(0.909, 1.063)",0.908714,1.062511,-1.754469e-02,3.988831e-02,6.600490e-01,0.660,False,ns,Not significant,1.739168e-02
31,diabetes_disease,0.984946,0.985,"(0.883, 1.098)",0.883455,1.098097,-1.516824e-02,5.548405e-02,7.845610e-01,0.785,False,ns,Not significant,1.505378e-02
4,shift_type_night,1.014957,1.015,"(0.951, 1.084)",0.950697,1.083561,1.484627e-02,3.337109e-02,6.564034e-01,0.656,False,ns,Not significant,1.495703e-02
36,dementia_disease,1.014751,1.015,"(0.868, 1.186)",0.868004,1.186308,1.464348e-02,7.969667e-02,8.542173e-01,0.854,False,ns,Not significant,1.475122e-02
40,atrial_fibrillation_disease,1.014079,1.014,"(0.932, 1.104)",0.931668,1.103780,1.398106e-02,4.324537e-02,7.464710e-01,0.746,False,ns,Not significant,1.407925e-02
3,shift_type_afternoon,1.013897,1.014,"(0.962, 1.068)",0.962383,1.068169,1.380157e-02,2.660480e-02,6.039265e-01,0.604,False,ns,Not significant,1.389725e-02
38,hemato_oncological_disease,0.987577,0.988,"(0.814, 1.199)",0.813612,1.198739,-1.250062e-02,9.886451e-02,8.993821e-01,0.899,False,ns,Not significant,1.242282e-02
24,prescription_day_WEEKEND,1.009705,1.010,"(0.955, 1.068)",0.954979,1.067567,9.658381e-03,2.843128e-02,7.340752e-01,0.734,False,ns,Not significant,9.705173e-03
27,hospital_days,1.005694,1.006,"(1.004, 1.008)",1.003655,1.007736,5.677479e-03,1.035339e-03,4.165454e-08,< 0.001,True,***,slightly increases odds,5.693626e-03
28,charlson_score,0.999253,0.999,"(0.958, 1.042)",0.957899,1.042392,-7.472516e-04,2.156441e-02,9.723572e-01,0.972,False,ns,Not significant,7.469725e-04
26,age,1.000294,1.000,"(0.999, 1.002)",0.998804,1.001786,2.940145e-04,7.605255e-04,6.990569e-01,0.699,False,ns,Not significant,2.940577e-04
2,gender_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,-1.855389e-15,3.050758e-15,5.430727e-01,0.543,False,ns,Not significant,1.887379e-15
5,shift_type_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,9.542995e-16,9.835128e-16,3.318985e-01,0.332,False,ns,Not significant,8.881784e-16
14,hospital_category_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,5.505660e-16,1.770528e-16,1.873318e-03,0.002,True,**,slightly increases odds,4.440892e-16
23,atc_group_ud_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,-2.127784e-16,4.373593e-17,1.144159e-06,< 0.001,True,***,slightly decreases odds,2.220446e-16
25,prescription_day_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,-9.323242e-17,4.236295e-17,2.775010e-02,0.028,True,*,slightly decreases odds,1.110223e-16
17,chronic_med_ud_Other,1.000000,1.000,"(1.000, 1.000)",1.000000,1.000000,-8.491881e-17,5.776772e-17,1.415606e-01,0.142,False,ns,Not significant,1.110223e-16

In [21]:
train_df[config['feature_columns']].value_counts()

age   gender  hospital_days  charlson_score  shift_type  unit_category_ud  hospital_category  chronic_med_ud  atc_group_ud                     prescription_day  kidney_disease  hepatic_disease  diabetes_disease  ischemic_heart_disease  copd_disease  cerebrovascular_disease  peptic_ulcer_disease  dementia_disease  oncological_disease  hemato_oncological_disease  hypertension_disease  atrial_fibrillation_disease  hyperlipidemia_disease  congestive_heart_failure_disease  obesity_disease
30.0  FEMALE  1              0               morning     Gynecology        Large hospitals    0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  21
29.0  FEMALE  1              0               morning     Gynecology        Large hospitals    0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  21
77.0  MALE    1              0               night       new_internal      Medium hospitals   >=5             OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  18
24.0  FEMALE  1              0               morning     Gynecology        Large hospitals    0               OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  18
80.0  MALE    1              0               afternoon   new_internal      Medium hospitals   >=5             OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                  18
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
19.0  MALE    1              0               morning     Emergency         Small hospitals    0               ANALGESICS                       WEEKEND           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                   1
                                                                                                                                               WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                   1
                                                         Surgery           Small hospitals    0               PSYCHOLEPTICS                    WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                   1
                                                                                                              ANTIBACTERIALS FOR SYSTEMIC USE  WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                   1
                                                                                                              OTHER                            WEEKDAY           0               0                0                 0                       0             0                        0                     0                 0                    0                           0                     0                            0                       0                                 0                   1
Name: count, Length: 134859, dtype: int64

In [21]:
# test_code